version: "3.5"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:21.8
    user: "${UID:?You must do 'export UID' to launch}"
    ports:
    - "9000:9000" 
    volumes:
    - "./rollup.xml:/etc/clickhouse-server/config.d/rollup.xml"
    - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    - "./data/clickhouse:/var/lib/clickhouse"
    networks:
      - graphite-clickhouse-tldr
  carbon-clickhouse:
    image: ghcr.io/lomik/carbon-clickhouse:0.11.2
    user: "${UID:?You must do 'export UID' to launch}"
    volumes:
    - "./data:/data"
    - "./carbon-clickhouse.conf:/etc/carbon-clickhouse/carbon-clickhouse.conf"
    ports:
    - "2003:2003" # plain tcp
    - "2003:2003/udp" # plain udp
    - "2004:2004" # pickle
    - "2006:2006" # prometheus remote write
    networks:
      - graphite-clickhouse-tldr
  graphite-clickhouse:
    image: ghcr.io/lomik/graphite-clickhouse:0.13.2
    volumes:
    - "./rollup.xml:/etc/graphite-clickhouse/rollup.xml"
    - "./graphite-clickhouse.conf:/etc/graphite-clickhouse/graphite-clickhouse.conf"
    networks:
      - graphite-clickhouse-tldr
  graphite-web:
    image: graphiteapp/graphite-statsd:1.1.8-1
    volumes:
    - "./graphiteweb_entrypoint.sh:/entrypoint.sh"
    - "./graphiteweb.conf:/opt/graphite/webapp/graphite/local_settings.py"
    entrypoint: /entrypoint.sh
    networks:
      - graphite-clickhouse-tldr
    ports:
    - "8085:80" # http ui

  grafana:
    image: grafana/grafana:latest
    user: "${UID:?You must do 'export UID' to launch}"
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - graphite-clickhouse-tldr
    ports:
      - "3000:3000"
    depends_on:
      - graphite-web
    volumes:
      - ./resources/data/grafana:/var/lib/grafana
    restart: unless-stopped
    healthcheck:
      test: "curl -fsSL -o /dev/null http://localhost:3000/login"
      interval: 10s
      timeout: 1s
      retries: 3

networks:
  graphite-clickhouse-tldr:
